# Generated by Django 3.2.6 on 2021-08-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=900)),
                ('respuesta', models.CharField(max_length=900)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.tema')),
            ],
        ),
    ]
