# Generated by Django 3.2.6 on 2021-08-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivo',
            name='pregunta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reactivo',
            name='respuesta',
            field=models.TextField(),
        ),
    ]
